# Generated by Django 5.2.4 on 2025-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('farm_type', models.CharField(choices=[('crop', 'Crop Farming'), ('livestock', 'Livestock'), ('fishery', 'Fishery'), ('poultry', 'Poultry')], max_length=20)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
